### ISSUE TITLE
Auto-update is stuck

### ISSUE THREAD

**Issue by Twinsidesmirror** [Saltssaumure/ieytd-discord-theme#3] opened 2022-03-09 16:38 UTC
It's been saying it has been updated everyday for the past 2 weeks now. No updates actually is made on the repo

**Comment by Saltssaumure** [comment] 2022-03-09 16:58
That's very strange, I can definitely confirm that there have been no updates. Can you take a screenshot of the update message the next time you see it? Thanks in advance.

**Comment by Twinsidesmirror** [comment] 2022-03-09 17:03
It's.. literally every time I opened discord for the first time so
Forced refreshed the instance and here you go. Had Pios and IEYTD on.
![image](https://user-images.githubusercontent.com/67185469/157492696-87b16673-eab8-4129-a0d6-31c59225fa6d.png)

**Comment by Twinsidesmirror** [comment] 2022-03-09 17:03
I
fuck
my brain didn't work hooooold on

Edit: I am sorry if you saw that earlier

**Comment by Saltssaumure** [comment] 2022-03-09 17:06
Does that popup come from a plugin? I don't think I've ever seen it before.

**Comment by Twinsidesmirror** [comment] 2022-03-09 17:08
> Does that popup come from a plugin? I don't think I've ever seen it before.

Theme/Plugin Repo plugin yeah. It tries to download directly from the betterdiscord's site every time it detects a piece of code somewhere to be outdated or smth

**Comment by Saltssaumure** [comment] 2022-03-09 17:17
Hmm, I'm not sure what's up with that to be honest. There have been no updates since the theme was accepted to BetterDiscord website, and the theme itself is also auto-updating without need for plugins, so I have no idea what the plugin is picking up on.

**Comment by Saltssaumure** [comment] 2022-03-14 16:31
Closing for now as the issue appears to be caused by a plugin.

**Closed as completed by Saltssaumure** 2022-03-14 16:31 UTC
